services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: monabit
      POSTGRES_PASSWORD: monabit
      POSTGRES_DB: monabit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: unless-stopped
    ports:
      - 5005:80
      - 5006:443
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@local.dev"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
